version: '3.7'
services:
  postgres:
    image: postgres:14
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=scaneat
      - POSTGRES_PASSWORD=change-in-production
      - POSTGRES_DB=scaneat
    networks:
      - scaneat

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - scaneat

  scaneat:
    image: scaneat:latest
    build:
      context: .
    ports:
      - ${HOST_PORT:-3000}:${PORT:-3000}
    env_file:
      - .env
    networks:
      - scaneat
    
volumes:
  mongodb_data:
  redis_data:
  postgres:

networks:
  scaneat:
    name: scaneat
    driver: bridge