- hosts: all
  vars:
    deploy_folder: /home/techbridge/scaneat/scaneat

  tasks:
    - name: Run yarn install
      shell: docker run --rm -v {{ deploy_folder }}:/app -w /app node:16 bash -c "yarn install"

    - name: Run migration
      shell: docker run --rm --network scaneat -v {{ deploy_folder }}:/app -w /app node:16 bash -c "yarn migration:run"
