- hosts: all
  vars:
    deploy_folder: /home/ubuntu/scaneat/scaneat

  tasks:
    - name: Run yarn install
      shell: yarn install
      args:
        chdir: '{{deploy_folder}}'

    - name: Run migration
      shell: docker run --rm --network scaneat -v {{ deploy_folder }}:/app -w /app node:16 bash -c "yarn migration:run"
