export enum TableName {
  CITY = 'city',
  RESTAURANT = 'restaurant',
  USER = 'user',
  PRODUCT = 'product',
  CATEGORY = 'category',
  RESTAURANT_OWNER = 'restaurant_owner',
  RESTAURANT_STAFF = 'restaurant_staff',
  PHOTO = 'photo',
  ORDER = 'order',
  ORDER_ADDRESS = 'order_address',
  ORDER_PRODUCT = 'order_product',
  STAFF_ROLE = 'staff_role',
  TG_CHAT = 'tg_chat',
  ORDER_TRACK = 'order_track',
}
